/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as VerificarRouteImport } from './routes/verificar'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as CursosIndexRouteImport } from './routes/cursos.index'
import { Route as CursosSlugRouteImport } from './routes/cursos.$slug'
import { Route as CursosSlugCertificadoRouteImport } from './routes/cursos.$slug_.certificado'
import { Route as CursosSlugProvaRouteImport } from './routes/cursos.$slug_.prova'
import { Route as CursosSlugLicaoMLRouteImport } from './routes/cursos.$slug_.licao.$m.$l'
import { Route as CursosSlugQuizSemanaRouteImport } from './routes/cursos.$slug_.quiz-semana'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificarRoute = VerificarRouteImport.update({
  id: '/verificar',
  path: '/verificar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CursosIndexRoute = CursosIndexRouteImport.update({
  id: '/cursos/',
  path: '/cursos/',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosSlugRoute = CursosSlugRouteImport.update({
  id: '/cursos/$slug',
  path: '/cursos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosSlugCertificadoRoute = CursosSlugCertificadoRouteImport.update({
  id: '/cursos/$slug_/certificado',
  path: '/cursos/$slug/certificado',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosSlugProvaRoute = CursosSlugProvaRouteImport.update({
  id: '/cursos/$slug_/prova',
  path: '/cursos/$slug/prova',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosSlugLicaoMLRoute = CursosSlugLicaoMLRouteImport.update({
  id: '/cursos/$slug_/licao/$m/$l',
  path: '/cursos/$slug/licao/$m/$l',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosSlugQuizSemanaRoute = CursosSlugQuizSemanaRouteImport.update({
  id: '/cursos/$slug_/quiz-semana',
  path: '/cursos/$slug/quiz-semana',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/playground': typeof PlaygroundRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/verificar': typeof VerificarRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/cursos/': typeof CursosIndexRoute
  '/cursos/$slug/certificado': typeof CursosSlugCertificadoRoute
  '/cursos/$slug/prova': typeof CursosSlugProvaRoute
   '/cursos/$slug/licao/$m/$l': typeof CursosSlugLicaoMLRoute,
   '/cursos/$slug/quiz-semana': typeof CursosSlugQuizSemanaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/playground': typeof PlaygroundRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/verificar': typeof VerificarRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/cursos': typeof CursosIndexRoute
  '/cursos/$slug/certificado': typeof CursosSlugCertificadoRoute
  '/cursos/$slug/prova': typeof CursosSlugProvaRoute
   '/cursos/$slug/licao/$m/$l': typeof CursosSlugLicaoMLRoute,
   '/cursos/$slug/quiz-semana': typeof CursosSlugQuizSemanaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/playground': typeof PlaygroundRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/verificar': typeof VerificarRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/cursos/': typeof CursosIndexRoute
  '/cursos/$slug_/certificado': typeof CursosSlugCertificadoRoute
  '/cursos/$slug_/prova': typeof CursosSlugProvaRoute
   '/cursos/$slug_/licao/$m/$l': typeof CursosSlugLicaoMLRoute,
   '/cursos/$slug_/quiz-semana': typeof CursosSlugQuizSemanaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/entrar'
    | '/esqueci-senha'
    | '/playground'
    | '/redefinir-senha'
    | '/verificar'
    | '/painel'
    | '/cursos/$slug'
    | '/cursos/'
    | '/cursos/$slug/certificado'
    | '/cursos/$slug/prova'
    | '/cursos/$slug/licao/$m/$l'
    | '/cursos/$slug/quiz-semana'
    fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/entrar'
    | '/esqueci-senha'
    | '/playground'
    | '/redefinir-senha'
    | '/verificar'
    | '/painel'
    | '/cursos/$slug'
    | '/cursos'
    | '/cursos/$slug/certificado'
    | '/cursos/$slug/prova'
    | '/cursos/$slug/licao/$m/$l'
    | '/cursos/$slug/quiz-semana'
    id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/entrar'
    | '/esqueci-senha'
    | '/playground'
    | '/redefinir-senha'
    | '/verificar'
    | '/_authenticated/painel'
    | '/cursos/$slug'
    | '/cursos/'
    | '/cursos/$slug_/certificado'
    | '/cursos/$slug_/prova'
     | '/cursos/$slug_/licao/$m/$l'
     | '/cursos/$slug_/quiz-semana'
   fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  EntrarRoute: typeof EntrarRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  PlaygroundRoute: typeof PlaygroundRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  VerificarRoute: typeof VerificarRoute
  CursosSlugRoute: typeof CursosSlugRoute
  CursosIndexRoute: typeof CursosIndexRoute
  CursosSlugCertificadoRoute: typeof CursosSlugCertificadoRoute
  CursosSlugProvaRoute: typeof CursosSlugProvaRoute
   CursosSlugLicaoMLRoute: typeof CursosSlugLicaoMLRoute,
   CursosSlugQuizSemanaRoute: typeof CursosSlugQuizSemanaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verificar': {
      id: '/verificar'
      path: '/verificar'
      fullPath: '/verificar'
      preLoaderRoute: typeof VerificarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/cursos/': {
      id: '/cursos/'
      path: '/cursos'
      fullPath: '/cursos/'
      preLoaderRoute: typeof CursosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/$slug': {
      id: '/cursos/$slug'
      path: '/cursos/$slug'
      fullPath: '/cursos/$slug'
      preLoaderRoute: typeof CursosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/$slug_/certificado': {
      id: '/cursos/$slug_/certificado'
      path: '/cursos/$slug/certificado'
      fullPath: '/cursos/$slug/certificado'
      preLoaderRoute: typeof CursosSlugCertificadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/$slug_/prova': {
      id: '/cursos/$slug_/prova'
      path: '/cursos/$slug/prova'
      fullPath: '/cursos/$slug/prova'
      preLoaderRoute: typeof CursosSlugProvaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/$slug_/licao/$m/$l': {
      id: '/cursos/$slug_/licao/$m/$l'
      path: '/cursos/$slug/licao/$m/$l'
      fullPath: '/cursos/$slug/licao/$m/$l'
      preLoaderRoute: typeof CursosSlugLicaoMLRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/$slug_/quiz-semana': {
      id: '/cursos/$slug_/quiz-semana'
      path: '/cursos/$slug/quiz-semana'
      fullPath: '/cursos/$slug/quiz-semana'
      preLoaderRoute: typeof CursosSlugQuizSemanaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  EntrarRoute: EntrarRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  PlaygroundRoute: PlaygroundRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  VerificarRoute: VerificarRoute,
  CursosSlugRoute: CursosSlugRoute,
  CursosIndexRoute: CursosIndexRoute,
  CursosSlugCertificadoRoute: CursosSlugCertificadoRoute,
  CursosSlugProvaRoute: CursosSlugProvaRoute,
  CursosSlugLicaoMLRoute: CursosSlugLicaoMLRoute,
  CursosSlugQuizSemanaRoute: CursosSlugQuizSemanaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
